apiVersion: v1
kind: Namespace
metadata:
  name: platform-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: fulfillment
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
