apiVersion: v1
kind: Service
metadata:
  name: shipment-api-svc
  namespace: logistics
  labels:
    app: shipment-api
spec:
  selector:
    app: shipment-api
  ports:
  - port: 80
    targetPort: 80
