apiVersion: v1
kind: Service
metadata:
  name: gemma3-12b-ft
  namespace: ml-serving
  labels:
    app.kubernetes.io/name: gemma3-12b-ft
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gemma3-12b-ft
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
